version: '3'
services:
  django:
    restart: always
    image: artsiom24091/django:latest
    build: .
    container_name: django
    environment:
      SECRET_KEY: "0123456789abcdef0123456789abcdef"
      DEBUG: "True"
      SQL_ENGINE: "mssql"
      SQL_NAME: "test"
      SQL_USER: "root"
      SQL_PASSWORD: "just4Taqtile"
      SQL_HOST: "localhost"
      SQL_PORT: "3306"
    tty: true
    network_mode: host
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/database:/usr/src/app/database
  onvif:
    restart: always
    image: artsiom24091/onvif:latest
    build: .
    container_name: onvif
    environment:
      IP: "192.168.1.101"
    volumes:
      - /home/server/reps/images:/var/www/5scontrol/images
      - /home/server/reps/videos:/var/www/5scontrol/videos
    depends_on:
      - django
    tty: true
    network_mode: host
  face_recognition_queue:
    restart: always
    image: artsiom24091/face_recognition_queue:latest
    build: .
    container_name: face_recognition_queue
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/database/dataset:/usr/src/app/dataset
    tty: true
    network_mode: host
  proxy:
    restart: always
    image: artsiom24091/proxy:release
    build: .
    container_name: proxy
    ports:
      - "3066:3066"   
  algorithms:
    restart: always
    image: artsiom24091/algorithms:latest
    build: .
    container_name: algorithms
    tty: true
    network_mode: host
    depends_on:
      - django
    volumes:
      -  /home/server/reps/images:/var/www/5scontrol/images
      -  /home/server/reps/database/dataset:/var/www/5scontrol/dataset
  5scontrol_front:
    restart: always
    image: artsiom24091/5scontrol_front:latest
    build: .
    container_name: 5scontrol_front
    ports:
      - "3000:3000"
    depends_on:
      - django
