version: '3'
services:
  django:
    restart: always
    image: 5scontrol/django:latest
    build: .
    container_name: django
    environment:
      SECRET_KEY: "0123456789abcdef0123456789abcdef"
      DEBUG: "True"
      SERVER_URL: "http://192.168.1.110"
      IP: "192.168.1.110"
      EMULATE_DB: "True"
    tty: true
    network_mode: host
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/videos:/usr/src/app/videos
      -  /home/server/reps/database:/usr/src/app/database
      -  /home/server/reps/log:/usr/src/app/log
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: just4Taqtile
      POSTGRES_DB: fiveScontrol
    ports:
      - "5432:5432"
    volumes:
      - /home/server/reps/database/pgdata:/var/lib/postgresql/data/
  onvif:
    restart: always
    image: 5scontrol/onvif:latest
    build: .
    container_name: onvif
    environment:
      IP: "192.168.1.110"
    volumes:
      - /home/server/reps/images:/var/www/5scontrol/images
      - /home/server/reps/videos:/var/www/5scontrol/videos
      - /home/server/reps/database:/var/www/5scontrol/database
    depends_on:
      - django
    tty: true
    network_mode: host
  algorithms-controller:
    restart: always
    image: 5scontrol/algorithms-controller:latest
    privileged: true
    build: .
    container_name: algorithms-controller
    tty: true
    network_mode: host
    environment:
      IP: "192.168.1.110"
      MIN_MAX_PYTHON: "True"
      IDLE_PYTHON: "True"
    depends_on:
      - django
    volumes:
      -  /home/server/reps/images:/var/www/5scontrol/images
      -  /home/server/reps/database/dataset:/var/www/5scontrol/dataset
      -  /home/server/reps/debug:/var/www/5scontrol/debug
      -  /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
  min_max_model:
    restart: always
    image: 5scontrol/min_max_python-server:v0.4.4
    build: .
    container_name: min_max_model
    tty: true
    network_mode: host
    environment:
      server_url: "192.168.1.110"
  machine_model:
    restart: always
    image: 5scontrol/machine_control_python_model_server:v1.0.0
    build: .
    container_name: machine_model
    tty: true
    network_mode: host
    environment:
      server_url: "192.168.1.110"
  idle_model:
    restart: always
    image: 5scontrol/idle_python_server:v0.4.4
    build: .
    container_name: idle_model
    tty: true
    network_mode: host
    environment:
      server_url: "192.168.1.110"
  5scontrol_front:
    restart: always
    image: 5scontrol/5scontrol_front:latest
    build: .
    container_name: 5scontrol_front
    ports:
      - "3000:3000"
    depends_on:
      - django
  onviffinder:
    image: 5scontrol/onviffinder:latest
    container_name: onvif_finder
    network_mode: host
    tty: true
    environment:
      IP: "192.168.1.110"
  emulate_operation_control:
    image: nnnxion/emulate_operation_control
    container_name: operation_report_handler
    network_mode: host
    tty: true
    environment:
      DB_SERVER: "192.168.1.110"
      DB_DATABASE: "test"
      DB_USERNAME: "sa"
      DB_PASS: "just4Taqtile"
  redis:
    image: redis
    container_name: redis
    command: redis-server --maxmemory-policy volatile-ttl
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=250
  tests:
    restart: always
    image: 5scontrol/tests:latest
    container_name: tests
    build: .
    ports:
      - "7000:7000"
    environment:
      BACKEND_PORT: 80
      IP: "192.168.1.110"
