version: '3'
services:
  tracker_and_sender:
    restart: always
    image: artsiom24091/tracker_and_sender:latest
    build: .
    container_name: tracker_and_sender
    ports:
      - "3011:3011"
    depends_on:
      - django
    environment:
      CAMERA_URLS: 'rtsp://admin:just4Taqtile@192.168.1.160/h264_stream rtsp://admin:just4Taqtile@192.168.1.161/h264_stream'
      CAMERA_TYPES: 'exit entrance'
    volumes:
      -  /home/server/reps/images:/var/www/5scontrol/images
      -  /home/server/reps/database/dataset:/var/www/5scontrol/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  django:
    restart: always
    image: artsiom24091/django:latest
    build: .
    container_name: django
    ports:
      - "80:8000"
    environment:
      SECRET_KEY: "django-insecure-osfh^r%nvpun6ek2z4n!f*&r@$g+*d8n#8z0ac9_%)%api0x)7"
      DEBUG: "True"
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/database:/usr/src/app/database
  face_recognition_queue:
    restart: always
    image: artsiom24091/face_recognition_queue:latest
    build: .
    container_name: face_recognition_queue
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8008:8008"
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/database/dataset:/usr/src/app/dataset
  redis:
    image: redis:6-alpine
  proxy:
    restart: always
    image: artsiom24091/proxy:latest
    build: .
    container_name: proxy
    ports:
      - "3066:3066"
