version: '3'
services:
  django:
    restart: always
    image: artsiom24091/django:latest
    build: .
    container_name: django
    environment:
      SECRET_KEY: "0123456789abcdef0123456789abcdef"
      DEBUG: "True"
      ALGORITHM_URL: "http://192.168.1.110"
      IP: "192.168.1.110"
    tty: true
    network_mode: host
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/videos:/usr/src/app/videos
      -  /home/server/reps/database:/usr/src/app/database
  onvif:
    restart: always
    image: artsiom24091/onvif:latest
    build: .
    container_name: onvif
    environment:
      IP: "192.168.1.110"
    volumes:
      - /home/server/reps/images:/var/www/5scontrol/images
      - /home/server/reps/videos:/var/www/5scontrol/videos
      - /home/server/reps/database:/var/www/5scontrol/database
    depends_on:
      - django
    tty: true
    network_mode: host
  proxy:
    restart: always
    image: artsiom24091/proxy:release
    build: .
    container_name: proxy
    ports:
      - "3066:3066"   
  algorithms:
    restart: always
    image: artsiom24091/algorithms:latest
    build: .
    container_name: algorithms
    tty: true
    network_mode: host
    depends_on:
      - django
    volumes:
      -  /home/server/reps/images:/var/www/5scontrol/images
      -  /home/server/reps/database/dataset:/var/www/5scontrol/dataset
  5scontrol_front:
    restart: always
    image: artsiom24091/5scontrol_front:latest
    build: .
    container_name: 5scontrol_front
    ports:
      - "3000:3000"
    depends_on:
      - django
  onviffinder:
    image: nnnxion/onviffinder:latest
    ports:
      - "7654:7654"
    network_mode: host
