apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos
  labels:
    type: local
spec:
  capacity:
    storage: 2000Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  local:
    path: /media/big/videos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server
