apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/server--default: "true"
        io.kompose.service: django
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "True"
            - name: EMULATE_DB
              value: "True"
            - name: IP
              value: 192.168.1.110
            - name: SECRET_KEY
              value: 0123456789abcdef0123456789abcdef
            - name: SERVER_URL
              value: http://192.168.1.110
          image: 5scontrol/django:latest
          name: django
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: django-claim0
            - mountPath: /usr/src/app/videos
              name: django-claim1
            - mountPath: /usr/src/app/database
              name: django-claim2
            - mountPath: /usr/src/app/log
              name: django-claim3
      restartPolicy: Always
      volumes:
        - name: django-claim0
          persistentVolumeClaim:
            claimName: django-claim0
        - name: django-claim1
          persistentVolumeClaim:
            claimName: django-claim1
        - name: django-claim2
          persistentVolumeClaim:
            claimName: django-claim2
        - name: django-claim3
          persistentVolumeClaim:
            claimName: django-claim3
status: {}
