apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: tests
  name: tests
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tests
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/server--default: "true"
        io.kompose.service: tests
    spec:
      containers:
        - env:
            - name: BACKEND_PORT
              value: "80"
            - name: IP
              value: 192.168.1.110
          image: 5scontrol/tests:latest
          name: tests
          ports:
            - containerPort: 7000
              hostPort: 7000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
