apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorithms-controller
  labels:
    deployment: algorithms-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: algorithms-controller
  template:
    metadata:
      labels:
        pod: algorithms-controller
      annotations:
        custom-label: '102424483666'
    spec:
      containers:
        - name: algorithms-controller
          image: 5scontrol/algorithms-controller:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: images
              mountPath: /var/www/5scontrol/images
            - name: docker
              mountPath: /var/run
          ports:
            - containerPort: 3333
              hostPort: 3333
              protocol: TCP
          env:
            - name: IDLE_PYTHON
              value: 'True'
            - name: ONVIF_SERVICE_URL
              value: onvif-service
            - name: DJANGO_SERVICE_URL
              value: django-service
            - name: MIN_MAX_PYTHON
              value: 'True'
            - name: K8S
              value: 'True'
            - name: K8S_MASTER_IP
              value: 192.168.1.115
      nodeSelector:
        specialnode: main
      restartPolicy: Always
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images
        - name: docker
          persistentVolumeClaim:
            claimName: docker
