apiVersion: v1
kind: Service
metadata:
  name: algorithms-controller-service
  namespace: default
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    pod: algorithms-controller
  type: ClusterIP