apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    pod: nginx
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30036
status:
  loadBalancer: {}