apiVersion: v1
kind: Service
metadata:
  name: onvif-service
  namespace: default
spec:
  selector:
    pod: onvif
  ports:
  - name: "3456"
    port: 3456
    targetPort: 3456
status:
  loadBalancer: {}