version: '3'
services:
  django:
    restart: always
    image: 5scontrol/django:v0.3.6
    build: .
    container_name: django
    environment:
      SECRET_KEY: "0123456789abcdef0123456789abcdef"
      DEBUG: "True"
      SERVER_URL: "http://192.168.1.184"
      IP: "192.168.1.184"
      PRODUCTION: "False"
    tty: true
    network_mode: host
    volumes:
      -  /home/server/reps/images:/usr/src/app/images
      -  /home/server/reps/videos:/usr/src/app/videos
      -  /home/server/reps/database:/usr/src/app/database
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: just4Taqtile
      POSTGRES_DB: fiveScontrol
    ports:
      - "5432:5432"
    volumes:
      - /home/server/reps/database/pgdata:/var/lib/postgresql/data/
  onvif:
    restart: always
    image: 5scontrol/onvif:v0.3.6
    build: .
    container_name: onvif
    environment:
      IP: "192.168.1.184"
    volumes:
      - /home/server/reps/images:/var/www/5scontrol/images
      - /home/server/reps/videos:/var/www/5scontrol/videos
      - /home/server/reps/database:/var/www/5scontrol/database
    depends_on:
      - django
    tty: true
    network_mode: host
  algorithms:
    restart: always
    image: 5scontrol/algorithms:v0.3.6
    privileged: true
    build: .
    container_name: algorithms
    tty: true
    network_mode: host
    environment:
      IP: "192.168.1.184"
      MIN_MAX_PYTHON: "True"
      IDLE_PYTHON: "True"
    depends_on:
      - django
    volumes:
      -  /home/server/reps/images:/var/www/5scontrol/images
      -  /home/server/reps/database/dataset:/var/www/5scontrol/dataset
      -  /home/server/reps/debug:/var/www/5scontrol/debug
      -  /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
  5scontrol_front:
    restart: always
    image: 5scontrol/5scontrol_front:v0.3.6
    build: .
    container_name: 5scontrol_front
    ports:
      - "3000:3000"
    depends_on:
      - django
  onviffinder:
    image: nnnxion/onviffinder:latest
    container_name: onvif_finder
    network_mode: host
    tty: true
    environment:
      IP: "192.168.1.184"
  emulate_operation_control:
    image: nnnxion/emulate_operation_control
    container_name: operation_report_handler
    network_mode: host
    tty: true
    environment:
      DB_SERVER: "192.168.1.184"
      DB_DATABASE: "test"
      DB_USERNAME: "sa"
      DB_PASS: "just4Taqtile"
  redis:
    image: redis
    command: redis-server --maxmemory-policy volatile-ttl
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=250
